import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/layout/navBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
        <div className="flex items-center justify-center px-20">
         {children}
        </div>
        <div className="h-30 w-full bg-gray-800 flex item-center justify-center">
          <div>
            <h1 className="text-white font-bold">FOOTER</h1>
          </div>
        </div>
      </body>
    </html>
  );
}
